# Generated by Django 5.2.17 on 2026-09-16 09:01

import django.db.models.deletion
import trade.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Optional override; otherwise the page title and EuroAfrica are used.', max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('social_image', models.ImageField(blank=True, help_text='JPEG, PNG or WebP; maximum 6 MB. Use a landscape image. Uploaded images are resized for the web.', upload_to='content/%Y/%m/', validators=[trade.validators.validate_image])),
                ('social_image_alt', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='A conversation starts here', max_length=180)),
                ('introduction', models.TextField(default='Tell us which trade category interests you and what you would like to know. Please avoid including sensitive personal information.')),
                ('confirmation', models.TextField(default='Thank you. Your enquiry has been saved for the EuroAfrica team.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Optional override; otherwise the page title and EuroAfrica are used.', max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('social_image', models.ImageField(blank=True, help_text='JPEG, PNG or WebP; maximum 6 MB. Use a landscape image. Uploaded images are resized for the web.', upload_to='content/%Y/%m/', validators=[trade.validators.validate_image])),
                ('social_image_alt', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('indexable', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, help_text='JPEG, PNG or WebP; maximum 6 MB. Use a landscape image. Uploaded images are resized for the web.', upload_to='content/%Y/%m/', validators=[trade.validators.validate_image])),
                ('image_alt', models.CharField(blank=True, max_length=240)),
                ('slug', models.SlugField(choices=[('about', 'About'), ('privacy', 'Privacy')], unique=True)),
                ('body', models.TextField(help_text='Plain text; separate paragraphs with blank lines.')),
            ],
            options={
                'ordering': ['order', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Optional override; otherwise the page title and EuroAfrica are used.', max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('social_image', models.ImageField(blank=True, help_text='JPEG, PNG or WebP; maximum 6 MB. Use a landscape image. Uploaded images are resized for the web.', upload_to='content/%Y/%m/', validators=[trade.validators.validate_image])),
                ('social_image_alt', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_heading', models.CharField(default='Connecting Africa and Europe Through Trade', max_length=180)),
                ('hero_text', models.TextField(default='Explore the products and sectors connecting African and European markets—from fresh produce and specialty goods to machinery, technology, and industrial supplies.')),
                ('hero_image', models.ImageField(blank=True, help_text='JPEG, PNG or WebP; maximum 6 MB. Use a landscape image. Uploaded images are resized for the web.', upload_to='content/%Y/%m/', validators=[trade.validators.validate_image])),
                ('hero_alt', models.CharField(blank=True, max_length=240)),
                ('primary_label', models.CharField(default='Explore Trade Categories', max_length=80)),
                ('primary_url', models.CharField(default='/#trade-directions', max_length=200, validators=[trade.validators.validate_destination])),
                ('secondary_label', models.CharField(default='Contact Us', max_length=80)),
                ('secondary_url', models.CharField(default='/contact/', max_length=200, validators=[trade.validators.validate_destination])),
                ('direction_heading', models.CharField(default='Two continents. A world of possibilities.', max_length=180)),
                ('direction_text', models.TextField(default='Discover the categories connecting markets in both directions.')),
                ('about_heading', models.CharField(default='A shared perspective on trade', max_length=180)),
                ('about_text', models.TextField(default='EuroAfrica brings together an introduction to the products and sectors linking Africa and Europe. Explore each trade direction to understand the breadth of categories represented here.')),
                ('diversity_heading', models.CharField(default='From the everyday to the exceptional', max_length=180)),
                ('diversity_text', models.TextField(default='Fresh flowers and food. Handcrafted textiles and personal care. Machinery and industrial technology. Explore a diverse range of categories, each with its own materials, applications and considerations.')),
                ('diversity_image', models.ImageField(blank=True, help_text='JPEG, PNG or WebP; maximum 6 MB. Use a landscape image. Uploaded images are resized for the web.', upload_to='content/%Y/%m/', validators=[trade.validators.validate_image])),
                ('diversity_alt', models.CharField(blank=True, max_length=240)),
                ('show_about', models.BooleanField(default=True)),
                ('show_diversity', models.BooleanField(default=True)),
                ('contact_heading', models.CharField(default='Let’s start a conversation', max_length=180)),
                ('contact_text', models.TextField(default='Interested in a category? Share your question with EuroAfrica.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Optional override; otherwise the page title and EuroAfrica are used.', max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('social_image', models.ImageField(blank=True, help_text='JPEG, PNG or WebP; maximum 6 MB. Use a landscape image. Uploaded images are resized for the web.', upload_to='content/%Y/%m/', validators=[trade.validators.validate_image])),
                ('social_image_alt', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='EuroAfrica', max_length=100)),
                ('tagline', models.CharField(default='Bridging Markets • Creating Opportunities', max_length=180)),
                ('header_logo', models.ImageField(blank=True, help_text='JPEG, PNG or WebP; maximum 6 MB. Use a landscape image. Uploaded images are resized for the web.', upload_to='content/%Y/%m/', validators=[trade.validators.validate_image])),
                ('footer_logo', models.ImageField(blank=True, help_text='JPEG, PNG or WebP; maximum 6 MB. Use a landscape image. Uploaded images are resized for the web.', upload_to='content/%Y/%m/', validators=[trade.validators.validate_image])),
                ('logo_alt', models.CharField(default='EuroAfrica', max_length=200)),
                ('favicon', models.ImageField(blank=True, help_text='JPEG, PNG or WebP; maximum 6 MB. Use a landscape image. Uploaded images are resized for the web.', upload_to='content/%Y/%m/', validators=[trade.validators.validate_image])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('address', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('footer_copy', models.CharField(default='An introduction to the products and sectors connecting African and European markets.', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Optional override; otherwise the page title and EuroAfrica are used.', max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('social_image', models.ImageField(blank=True, help_text='JPEG, PNG or WebP; maximum 6 MB. Use a landscape image. Uploaded images are resized for the web.', upload_to='content/%Y/%m/', validators=[trade.validators.validate_image])),
                ('social_image_alt', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180)),
                ('summary', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('indexable', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, help_text='JPEG, PNG or WebP; maximum 6 MB. Use a landscape image. Uploaded images are resized for the web.', upload_to='content/%Y/%m/', validators=[trade.validators.validate_image])),
                ('image_alt', models.CharField(blank=True, max_length=240)),
                ('overview', models.TextField()),
                ('hero_image', models.ImageField(blank=True, help_text='JPEG, PNG or WebP; maximum 6 MB. Use a landscape image. Uploaded images are resized for the web.', upload_to='content/%Y/%m/', validators=[trade.validators.validate_image])),
                ('hero_alt', models.CharField(blank=True, max_length=240)),
                ('featured', models.BooleanField(default=False)),
                ('editorial_notes', models.TextField(blank=True, help_text='Internal only. Never displayed on the public site.')),
            ],
            options={
                'verbose_name_plural': 'Trade categories',
                'ordering': ['order', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradeDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Optional override; otherwise the page title and EuroAfrica are used.', max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('social_image', models.ImageField(blank=True, help_text='JPEG, PNG or WebP; maximum 6 MB. Use a landscape image. Uploaded images are resized for the web.', upload_to='content/%Y/%m/', validators=[trade.validators.validate_image])),
                ('social_image_alt', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('indexable', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, help_text='JPEG, PNG or WebP; maximum 6 MB. Use a landscape image. Uploaded images are resized for the web.', upload_to='content/%Y/%m/', validators=[trade.validators.validate_image])),
                ('image_alt', models.CharField(blank=True, max_length=240)),
                ('slug', models.SlugField(unique=True)),
                ('introduction', models.TextField()),
            ],
            options={
                'ordering': ['order', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='URLHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True)),
                ('kind', models.CharField(max_length=30)),
                ('object_id', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=180)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('message', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('staff_notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.tradecategory')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=180)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='trade.tradecategory')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='JPEG, PNG or WebP; maximum 6 MB. Use a landscape image. Uploaded images are resized for the web.', upload_to='content/%Y/%m/', validators=[trade.validators.validate_image])),
                ('image_alt', models.CharField(blank=True, max_length=240)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='trade.tradecategory')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='JPEG, PNG or WebP; maximum 6 MB. Use a landscape image. Uploaded images are resized for the web.', upload_to='content/%Y/%m/', validators=[trade.validators.validate_image])),
                ('image_alt', models.CharField(max_length=240)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='trade.tradecategory')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='tradecategory',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='trade.tradedirection'),
        ),
        migrations.AddConstraint(
            model_name='tradecategory',
            constraint=models.UniqueConstraint(fields=('direction', 'slug'), name='category_direction_slug'),
        ),
    ]
