# Generated by Django 5.2.17 on 2026-09-16 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionwindow',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
