# Generated by Django 5.2.17 on 2026-09-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_submissionwindow_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradecategory',
            name='seed_key',
            field=models.CharField(blank=True, editable=False, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tradedirection',
            name='seed_key',
            field=models.CharField(blank=True, editable=False, max_length=180, null=True, unique=True),
        ),
    ]
