# Generated by Django 5.2.17 on 2026-09-16 22:39

import trade.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_tradecategory_seed_key_tradedirection_seed_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('destination', models.CharField(help_text='A local website path, for example /contact/. Unpublished page links are hidden automatically.', max_length=250, validators=[trade.validators.validate_destination])),
                ('group', models.CharField(choices=[('explore', 'Explore'), ('trade', 'Trade directions'), ('legal', 'Legal')], default='explore', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['group', 'order', 'pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'Brand, footer & SEO settings'},
        ),
        migrations.AddField(
            model_name='categoryimage',
            name='image_position',
            field=models.CharField(choices=[('center', 'Centre'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='image_caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='image_position',
            field=models.CharField(choices=[('center', 'Centre'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='image_caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='image_position',
            field=models.CharField(choices=[('center', 'Centre'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='diversity_caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='diversity_position',
            field=models.CharField(choices=[('center', 'Centre'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_position',
            field=models.CharField(choices=[('center', 'Centre'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_copy',
            field=models.CharField(blank=True, default='Bridging continents. Connecting perspectives.', max_length=240),
        ),
        migrations.AddField(
            model_name='tradecategory',
            name='hero_caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='tradecategory',
            name='hero_position',
            field=models.CharField(choices=[('center', 'Centre'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='tradecategory',
            name='image_caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='tradecategory',
            name='image_position',
            field=models.CharField(choices=[('center', 'Centre'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='tradedirection',
            name='image_caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='tradedirection',
            name='image_position',
            field=models.CharField(choices=[('center', 'Centre'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=10),
        ),
    ]
