# Generated by Django 5.2.17 on 2026-09-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_required_site_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockImageInitialization',
            fields=[
                ('key', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
