# Generated by Django 5.2.17 on 2026-09-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_stockimageinitialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionReceipt',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='enquiry',
            name='privacy_consent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('read', 'Read'), ('replied', 'Replied'), ('spam', 'Spam'), ('archived', 'Archived')], default='new', max_length=20),
        ),
    ]
