# Generated by Django 5.2.17 on 2026-09-19 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_category_guidance'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='interest',
            field=models.CharField(choices=[('general', 'General Enquiry'), ('africa-to-europe', 'Africa → Europe Trade'), ('europe-to-africa', 'Europe → Africa Trade')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='market',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='final_heading',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='homepage',
            name='final_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tradecategory',
            name='link_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tradedirection',
            name='heading',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=180)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='trade.contentpage')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=180)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='trade.homepage')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
