# Generated by Django 5.2.17 on 2026-10-02 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("trade", "0013_tobacco_brochure"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ar", "العربية"),
                            ("hu", "Magyar"),
                            ("uk", "Українська"),
                            ("fr", "Français"),
                            ("de", "Deutsch"),
                        ],
                        max_length=2,
                    ),
                ),
                ("field", models.CharField(max_length=60)),
                ("text", models.TextField()),
                ("source_text", models.TextField(editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={"app_label": "trade"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["content_type", "object_id", "language", "field"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "language", "field"),
                        name="unique_editorial_translation",
                    )
                ],
            },
        ),
    ]
