from django.core.management.base import BaseCommand
from django.contrib.auth.models import Group, Permission
from trade.models import *
from trade.category_guidance import GUIDANCE

DATA = [
('Cut Flowers', 'cut-flowers', ['Roses', 'Summer flowers', 'Alstroemeria'], 'Colour, form and seasonality connect the world of cut flowers—from familiar roses to summer flowers and alstroemeria.', 'Cut flowers bring together distinct shapes, stem structures and colour palettes for floral arrangements. Roses offer a recognisable focal flower; summer flowers introduce variety; alstroemeria adds clusters of patterned blooms.\n\nWhen discussing this category, identify the flower type, preferred colour and intended use. Variety, handling and timing are useful topics for a detailed enquiry.'),
('Fresh Fruits & Vegetables', 'fresh-fruits-vegetables', ['Avocados', 'Mangoes', 'Passion fruit', 'Green beans', 'Peas'], 'Explore a produce category spanning avocados, tropical fruits and green vegetables.', 'Avocados, mangoes and passion fruit sit alongside green beans and peas in this category. The examples represent different textures, preparation methods and uses, from fresh consumption to ingredients in cooking.\n\nA useful produce enquiry names the item and its intended application. Ripeness, presentation and handling requirements vary by product and should be discussed individually.'),
('Beverages', 'beverages', ['Premium black tea', 'Specialty purple tea', 'Kenyan coffee'], 'An introduction to premium black tea, specialty purple tea and Kenyan coffee.', 'Tea and coffee offer distinct ways to explore the beverage category. Premium black tea and specialty purple tea are presented alongside Kenyan coffee, retaining the specific origin named in the supplied category information.\n\nThese examples do not describe the origin of every African beverage. Enquiries can distinguish between tea and coffee and specify the desired format or intended use without assuming a particular grade or certification.'),
('Nuts', 'nuts', ['Macadamia nuts'], 'Macadamia nuts form the focus of this category, with uses as a snack and a food ingredient.', 'Macadamia nuts are valued in a range of food preparations, from simple snack formats to baking and confectionery. This category focuses on macadamias rather than implying a broader range of nuts.\n\nFor an enquiry, it helps to specify the intended preparation and whether the discussion concerns whole nuts or an ingredient format. Processing, packaging and allergen information need to be established for the particular product.'),
('Fish', 'fish', ['Nile perch', 'Other fish fillets'], 'Explore Nile perch and other fish fillets within the Africa-to-Europe category overview.', 'This category includes Nile perch as a named example, together with other fish fillets. Species and presentation are important distinctions; the general reference to fillets does not identify additional species or their origins.\n\nA category enquiry should name the fish where known and describe the required presentation. Handling, traceability and applicable requirements should be clarified before any specific trade discussion.'),
('Handicrafts & Textiles', 'handicrafts-textiles', ['Traditional jewellery', 'Woven baskets', 'Leather goods', 'Fabrics such as kikoys'], 'Materials and making take centre stage in jewellery, baskets, leather goods and fabrics such as kikoys.', 'Handicrafts and textiles bring together decorative and practical objects. Traditional jewellery, woven baskets, leather goods and fabrics such as kikoys each have distinct materials, construction methods and uses.\n\nThis overview does not attribute items to a particular maker or community. Enquiries can describe the object, material and intended use, with provenance and production details left for verification.'),
('Natural Cosmetics', 'natural-cosmetics', ['Essential oils', 'Soaps', 'Shea-based body creams'], 'A personal-care category covering essential oils, soaps and shea-based body creams.', 'Essential oils, soaps and shea-based body creams represent different product formats within personal care. Ingredient composition, fragrance and intended use help distinguish one item from another.\n\nThe category name is descriptive and does not establish organic certification, safety approval or therapeutic benefits. Specific ingredient lists, labelling and market requirements need to be checked for individual products.'),
('Machinery & Mechanical Appliances', 'machinery-mechanical-appliances', ['Boilers', 'Specialized factory machinery used in manufacturing and processing'], 'Explore boilers and specialized machinery for manufacturing and processing applications.', 'This category covers boilers and specialized factory machinery used in manufacturing and processing. The intended process is central to understanding a machine: equipment for one application may differ substantially from equipment for another.\n\nUseful enquiry details include the process, operating environment and technical specification. This overview does not confirm equipment availability, installation services or a particular manufacturer.'),
('Chemicals & Pharmaceuticals', 'chemicals-pharmaceuticals', ['Essential medicines', 'Vaccines', 'Chemical compounds', 'Agricultural fertilizers'], 'An overview of distinct categories spanning medicines, vaccines, chemical compounds and agricultural fertilizers.', 'Medicines and vaccines have different purposes and requirements from industrial chemical compounds or agricultural fertilizers. They are grouped here as supplied examples, while retaining those important distinctions.\n\nA specific enquiry should clearly identify the product type and intended application. This informational overview makes no claim of authorization to supply regulated products or of regulatory approval in any market.'),
('Electrical Equipment & Technology', 'electrical-equipment-technology', ['Industrial electronics', 'Telecommunications equipment', 'High-tech medical apparatus'], 'Industrial electronics, telecommunications equipment and high-tech medical apparatus connect this technology category.', 'Electrical equipment and technology span industrial control, communications and medical applications. The examples in this category are industrial electronics, telecommunications equipment and high-tech medical apparatus.\n\nTechnical compatibility, intended use and the operating setting are useful starting points for an enquiry. No particular brand, certification, support service or medical-device authorization is implied.'),
('Transportation & Vehicles', 'transportation-vehicles', ['Motor vehicles', 'Automotive spare parts', 'Aircraft equipment'], 'Explore motor vehicles, automotive spare parts and aircraft equipment as distinct transport-related categories.', 'Transportation encompasses complete motor vehicles as well as components and specialist aircraft equipment. These items serve different applications and should be identified separately in a detailed discussion.\n\nFor spare parts, precise part identification and compatibility are useful enquiry details. The category overview does not confirm a vehicle inventory, aircraft capability or maintenance service.'),
('Refined Petroleum & Minerals', 'refined-petroleum-minerals', ['Specialized oils', 'Distillation products'], 'Specialized oils and distillation products are the supplied examples within this industrial category.', 'The supplied category heading is broad; its named examples are specialized oils and distillation products. This page keeps the focus on those examples without introducing unconfirmed mineral types or additional petroleum products.\n\nThe intended application and relevant specification help distinguish materials within the category. Product composition, handling information and suitability require individual verification.'),
('Processed Foodstuffs & Wheat', 'processed-foodstuffs-wheat', ['Wheat and other cereals', 'Dairy items', 'European beverages and spirits'], 'A food and beverage overview spanning wheat, other cereals, dairy items, and European beverages and spirits.', 'Wheat and other cereals form one part of this category, alongside dairy items and European beverages and spirits. The range includes ingredients and finished food or beverage formats with different storage and presentation needs.\n\nEnquiries should identify the product and intended use. Labelling, ingredients and any market-specific requirements need to be considered for each item; this overview does not confirm specific brands or availability.')]

def seed_object(model, slug, defaults):
    obj = model.objects.filter(seed_key=slug).first() or model.objects.filter(slug=slug).first()
    if obj:
        if not obj.seed_key:
            model.objects.filter(pk=obj.pk).update(seed_key=slug)
        return obj, False
    return model.objects.create(seed_key=slug, slug=slug, **defaults), True

class Command(BaseCommand):
    help = 'Create approved starter content and permissions without replacing later owner edits.'
    def handle(self, *args, **options):
        from importlib import import_module
        from types import SimpleNamespace
        from django.apps import apps
        from django.db import connection
        import_module('trade.migrations.0011_approved_website_content').install(apps, SimpleNamespace(connection=connection), overwrite=False)
        ContentPage.objects.get_or_create(slug='privacy', defaults=dict(title='Privacy notice', summary='How enquiry data is handled.', body='OWNER REVIEW REQUIRED BEFORE PUBLICATION. Confirm controller identity, contact details, purposes, processors including Cloudflare verification and email delivery, retention, transfers and applicable rights. This is an unpublished editorial draft.', published=False))
        group, _ = Group.objects.get_or_create(name='Editor')
        names = ['sitesettings','homepage','contactpage','tradedirection','tradecategory','categoryproduct','categorysection','categoryimage','contentpage','enquiry','footerlink','homefeature','contentsection']
        group.permissions.add(*Permission.objects.filter(content_type__app_label='trade',content_type__model__in=names).exclude(codename='add_enquiry'))
        self.stdout.write(self.style.SUCCESS('Approved starter content and Editor permissions ready; existing edits preserved.'))
